/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package nl.info.gradle.plugin

import org.gradle.testkit.runner.GradleRunner
import java.io.File
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'nl.info.gradle.plugin.greeting' plugin.
 */
class RamlJavaClientGeneratorPluginFunctionalTest {
    @Test fun `can run task`() { // NOSONAR
        // Setup the test build
        val projectDir = File("build/functionalTest")
        projectDir.mkdirs()
        projectDir.resolve("settings.gradle").writeText("")
        projectDir.resolve("build.gradle").writeText("""
            plugins {
                id('nl.info.gradle.plugin.generateramljavaclient')
            }

            sourceSets {
                main {
                    generateramljavaclient {
                    }
                }
            }

            generateramljavaclient {
                targetVersion = "1_8"
                basePackage = "test"
                source = "risk-and-compliance-api.raml"
            }
        """)

        // Run the build
        val runner = GradleRunner.create()
                .forwardOutput()
                .withPluginClasspath()
                .withArguments("generateramljavaclient", "--stacktrace")
                .withProjectDir(projectDir)
        val result = runner.build()

        // Verify the result
        assertTrue(result.output.contains("Task :generateramljavaclient"))
    }
}
