/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package nl.info.gradle.plugin

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'nl.info.gradle.plugin.greeting' plugin.
 */
class RamlJavaClientGeneratorPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("nl.info.gradle.plugin.generateramljavaclient")

        // Verify the result
        assertNotNull(project.tasks.findByName("generateramljavaclient"))
    }
}
